project '什么值得买.xcodeproj'

# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'

target '什么值得买' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for 什么值得买
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod "AFNetworking"
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'SnapKit'
  pod 'SDCycleScrollView'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'ZYCornerRadius'
  pod 'YYKit'
  pod 'RongCloudIM/IMLib'
  pod 'RongCloudIM/IMKit'
  pod 'SVProgressHUD'
  pod 'FDFullscreenPopGesture'
  pod 'JSPatchPlatform'
  pod 'DZNEmptyDataSet'
  pod "CSStickyHeaderFlowLayout"
  pod 'WebViewJavascriptBridge'
  pod 'IQKeyboardManagerSwift'
  pod 'Bugly'
  pod 'SDiPhoneVersion'
  pod 'JPush'
  pod 'IGListKit'
  pod 'SwiftyJSON'
  
#  pod 'SwipeTableView'
  # 主模块(必须)
  pod 'ShareSDK3'
  # Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
  pod 'MOBFoundation'
  # UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
  pod 'ShareSDK3/ShareSDKUI'
  # 扩展模块（非必需）
  pod 'ShareSDK3/ShareSDKExtension'
  # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
  pod 'ShareSDK3/ShareSDKPlatforms/QQ'
  pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
  pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
  
end
